/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Event = {
  agent_id: AgentId;
  agent_version?: AgentVersion;
  attributes?: {
    "agent.child_id"?: string;
    "agent.state"?: string;
    "approval.capability"?: string;
    "approval.id"?: string;
    "cost.estimated_usd"?: number;
    "cost.pricing_version"?: string;
    "db.latency_ms"?: number;
    "db.operation"?: string;
    "db.rows_returned"?: number;
    "db.system"?: string;
    "file.hash_after"?: string;
    "file.hash_before"?: string;
    "file.language"?: string;
    "file.lines_added"?: number;
    "file.lines_removed"?: number;
    "file.path"?: string;
    "file.size_after"?: number;
    "file.size_before"?: number;
    "git.base_commit"?: string;
    "git.branch"?: string;
    "git.changed_files"?: number;
    "git.commit_hash"?: string;
    "git.head_commit"?: string;
    "git.pr_number"?: number;
    "git.push_target"?: string;
    "git.repo"?: string;
    "http.latency_ms"?: number;
    "http.method"?: string;
    "http.status_code"?: number;
    "http.url"?: string;
    "llm.cached_input_tokens"?: number;
    "llm.error_type"?: string;
    "llm.input_tokens"?: number;
    "llm.latency_ms"?: number;
    "llm.max_tokens"?: number;
    "llm.model"?: string;
    "llm.output_tokens"?: number;
    "llm.provider"?: string;
    "llm.temperature"?: number;
    "loop.pattern"?: string[];
    "loop.repetitions"?: number;
    "policy.capability"?: string;
    "policy.id"?: string;
    "policy.reason"?: string;
    "rate_limit.retry_after_ms"?: number;
    "retry.attempt"?: number;
    "retry.delay_ms"?: number;
    "retry.of_event_id"?: string;
    "retry.reason"?: string;
    "run.name"?: string;
    "secret.kind"?: string;
    "shell.command"?: string;
    "shell.cwd"?: string;
    "shell.duration_ms"?: number;
    "shell.exit_code"?: number;
    "shell.risk_class"?: string;
    "span.kind"?: string;
    "span.name"?: string;
    "test.failed"?: number;
    "test.failing"?: string[];
    "test.framework"?: string;
    "test.passed"?: number;
    "test.skipped"?: number;
    "test.total"?: number;
    "timeout.limit_ms"?: number;
    "timeout.operation"?: string;
    "tool.error_type"?: string;
    "tool.latency_ms"?: number;
    "tool.name"?: string;
    "tool.operation"?: string;
    "tool.result_count"?: number;
    [k: string]: string | number | boolean | (string | number | boolean)[] | string[] | undefined;
  };
  duration_ms?: DurationMs;
  event_id: EventId;
  event_type: EventType;
  occurred_at: string;
  parent_span_id?: ParentSpanId;
  payload?: Payload;
  payload_ref?: PayloadRef;
  project_id: ProjectId;
  received_at: string;
  run_id: RunId;
  schema_version: string;
  sdk?: SdkInfo | null;
  sequence?: Sequence;
  span_id?: SpanId;
  status?: EventStatus | null;
  tags?: Tags;
  trace_id: TraceId;
  workspace_id: WorkspaceId;
  [k: string]: unknown;
};
export type AgentId = string;
export type AgentVersion = string | null;
export type DurationMs = number | null;
export type EventId = string;
export type EventType = string;
export type ParentSpanId = string | null;
export type Payload = {
  [k: string]: unknown;
} | null;
export type PayloadRef = string | null;
export type ProjectId = string;
export type RunId = string;
export type Name = string;
export type Version = string;
export type Sequence = number | null;
export type SpanId = string | null;
/**
 * Outcome carried by completion-style events. Point events may omit it.
 */
export type EventStatus = "success" | "error" | "timeout" | "cancelled" | "blocked";
/**
 * @maxItems 16
 */
export type Tags =
  | []
  | [string]
  | [string, string]
  | [string, string, string]
  | [string, string, string, string]
  | [string, string, string, string, string]
  | [string, string, string, string, string, string]
  | [string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string, string, string]
  | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
  | [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ]
  | [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string
    ];
export type TraceId = string;
export type WorkspaceId = string;

export interface SdkInfo {
  name: Name;
  version: Version;
  [k: string]: unknown;
}
