/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/cost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where the money went
         * @description Cost per run, per successful run, by day, agent, model, project, the retry breakdown (spec §24) and the most expensive runs. Runs are placed in the window by `started_at`. Windows are whole UTC days: `from` rounds down and `to` rounds up. Default: the last 7 days; at most 92. Figures come from daily rollups that lag changes by up to about a minute. Percentiles are approximate (about 10%). A project-bound key is confined to its project.
         */
        get: operations["cost_v1_analytics_cost_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latency percentiles and the slowest operations
         * @description p50/p95 for runs, model calls and tools, and the slowest operations. Only tool and model spans are listed by name; other kinds are grouped by kind. Runs are placed in the window by `started_at`. Windows are whole UTC days: `from` rounds down and `to` rounds up. Default: the last 7 days; at most 92. Figures come from daily rollups that lag changes by up to about a minute. Percentiles are approximate (about 10%). A project-bound key is confined to its project.
         */
        get: operations["performance_v1_analytics_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/reliability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Failure trend, tool success and retry-heavy runs
         * @description Runs are placed in the window by `started_at`. Windows are whole UTC days: `from` rounds down and `to` rounds up. Default: the last 7 days; at most 92. Figures come from daily rollups that lag changes by up to about a minute. Percentiles are approximate (about 10%). A project-bound key is confined to its project.
         */
        get: operations["reliability_v1_analytics_reliability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Headline figures for a window
         * @description Run counts and rates, cost, run latency, behaviour averages. Runs are placed in the window by `started_at`. Windows are whole UTC days: `from` rounds down and `to` rounds up. Default: the last 7 days; at most 92. Figures come from daily rollups that lag changes by up to about a minute. Percentiles are approximate (about 10%). A project-bound key is confined to its project.
         */
        get: operations["summary_v1_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a single event */
        post: operations["ingest_event_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of events
         * @description Accepts `{batch_id?, sent_at?, events: [...]}` (at most 1000 events, 5 MiB, optionally gzip). `202` means the valid events are committed. Invalid events are reported per event in `errors` and do not affect the others. Retrying a batch is safe.
         */
        post: operations["ingest_batch_v1_events_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pricing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the prices used to compute cost
         * @description Built-in price entries plus the workspace's overrides (a project-bound key sees workspace-wide overrides and its own project's). Built-in entries are illustrative (KI-050).
         */
        get: operations["list_prices_v1_pricing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Newest first by default. Page with `next_cursor`; filters combine with AND.
         */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /**
         * Create a run explicitly
         * @description Optional: the first event for an unseen run id creates the run anyway. Idempotent on `run_id`. Needs a project-bound key with `events:write`.
         */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a run's events in canonical order
         * @description Ordered by sequence when every event of the run has one, otherwise by time (`ordering_mode`). Payloads are omitted; fetch one event for its payload.
         */
        get: operations["list_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one event, including its inline payload */
        get: operations["get_event_v1_runs__run_id__events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a run's spans
         * @description Derived from events; an empty list while the run is still `processing`.
         */
        get: operations["list_spans_v1_runs__run_id__spans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a run's events live (SSE)
         * @description Live events of one run as Server-Sent Events.
         *
         *     Messages: `event: trace_event` (`id:` is the event id, `data:` an event without payload, as in
         *     the list endpoint), `event: run_end` (the run finished and nothing arrived for a while: do not
         *     reconnect) and `event: error` (reconnect). `: keepalive` comments keep idle connections open. The
         *     server closes a stream after its maximum lifetime; reconnect with `Last-Event-ID`.
         *
         *     Resume with the `Last-Event-ID` header (browsers send it on reconnect) or `last_event_id` for the
         *     first connection. The server re-sends a short window of events already seen: de-duplicate by event
         *     id. Without either, the stream starts at the beginning of the run. Payloads are never streamed.
         */
        get: operations["stream_run_v1_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchResponse */
        BatchResponse: {
            /**
             * Accepted
             * @description Events stored by this request.
             */
            accepted: number;
            /** Batch Id */
            batch_id: string | null;
            /**
             * Conflicts
             * @description Events whose id exists with different content (kept first).
             */
            conflicts: number;
            /**
             * Duplicates
             * @description Events already stored with identical content.
             */
            duplicates: number;
            /** Errors */
            errors: components["schemas"]["EventErrorOut"][];
            /**
             * Rejected
             * @description Events that were not stored; see `errors`.
             */
            rejected: number;
            /** Request Id */
            request_id: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** Behaviour */
        Behaviour: {
            /** Avg Files Modified */
            avg_files_modified: number | null;
            /** Avg Llm Calls */
            avg_llm_calls: number | null;
            /** Avg Retries */
            avg_retries: number | null;
            /** Avg Tool Calls */
            avg_tool_calls: number | null;
        };
        /** CostByAgent */
        CostByAgent: {
            /** Agent */
            agent: string;
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
        };
        /** CostByDay */
        CostByDay: {
            /** Cost Usd */
            cost_usd: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Retry Usd */
            retry_usd: number;
            /** Runs */
            runs: number;
        };
        /** CostByModel */
        CostByModel: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Model */
            model: string | null;
            /** Output Tokens */
            output_tokens: number;
            /** Provider */
            provider: string | null;
            /** Unpriced Calls */
            unpriced_calls: number;
        };
        /** CostByProject */
        CostByProject: {
            /** Cost Usd */
            cost_usd: number;
            /** Project Id */
            project_id: string;
            /** Runs */
            runs: number;
        };
        /** CostBySource */
        CostBySource: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Source
             * @description provider_reported | estimated | client_estimate | unpriced
             */
            source: string;
        };
        /** CostHeadline */
        CostHeadline: {
            /** Per Run Usd */
            per_run_usd: number | null;
            /** Per Successful Run Usd */
            per_successful_run_usd: number | null;
            /**
             * Retry Share
             * @description retry_usd / total_usd
             */
            retry_share: number | null;
            /**
             * Retry Usd
             * @description Cost of model calls made after a retry (ADR-042).
             */
            retry_usd: number;
            /** Total Usd */
            total_usd: number;
            /**
             * Unpriced Calls
             * @description Model calls with no usable cost; counted as $0.
             */
            unpriced_calls: number;
            /**
             * Unrebuilt Runs
             * @description Runs summarized before cost lines existed; `rebuild-costs` fills them in.
             */
            unrebuilt_runs: number;
        };
        /** CostReport */
        CostReport: {
            /** By Agent */
            by_agent: components["schemas"]["CostByAgent"][];
            by_agent_other: components["schemas"]["OtherBucket"] | null;
            /** By Day */
            by_day: components["schemas"]["CostByDay"][];
            /** By Model */
            by_model: components["schemas"]["CostByModel"][];
            by_model_other: components["schemas"]["OtherBucket"] | null;
            /**
             * By Project
             * @description Only when the query is not limited to one project.
             */
            by_project: components["schemas"]["CostByProject"][] | null;
            /** By Source */
            by_source: components["schemas"]["CostBySource"][];
            /** Expensive Runs */
            expensive_runs: components["schemas"]["ExpensiveRun"][];
            headline: components["schemas"]["CostHeadline"];
            retries: components["schemas"]["RetryBreakdown"];
            window: components["schemas"]["Window"];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Agent Id */
            agent_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            category: components["schemas"]["ErrorCategory"];
            /**
             * Code
             * @description Stable machine-readable code, e.g. RUN_NOT_FOUND.
             */
            code: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Request Id
             * @description Also in the X-Request-ID response header.
             */
            request_id: string | null;
            /**
             * Retryable
             * @description Whether retrying the same request may succeed.
             */
            retryable: boolean;
        };
        /**
         * ErrorCategory
         * @enum {string}
         */
        ErrorCategory: "AUTHENTICATION" | "AUTHORIZATION" | "VALIDATION" | "RATE_LIMIT" | "DEPENDENCY" | "TIMEOUT" | "CONFLICT" | "NOT_FOUND" | "POLICY" | "INTERNAL";
        /**
         * ErrorEnvelope
         * @description The one error shape of every non-2xx response (spec §101.2).
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * EventErrorOut
         * @description Why one event of a batch was not stored.
         */
        EventErrorOut: {
            /** Code */
            code: string;
            /**
             * Event Id
             * @description The event's id, when it was readable.
             */
            event_id: string | null;
            /**
             * Index
             * @description Position of the event in the submitted `events` array.
             */
            index: number;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["IssueOut"][];
        };
        /**
         * EventOut
         * @description A stored event as returned by the API. `payload` is only present on the detail endpoint.
         */
        EventOut: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version?: string | null;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms?: number | null;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Has Payload */
            has_payload: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Payload
             * @description Inline payload; omitted from lists (`has_payload` says if present).
             */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Payload Ref */
            payload_ref?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Sdk */
            sdk?: {
                [key: string]: unknown;
            } | null;
            /** Sequence */
            sequence?: number | null;
            /** Span Id */
            span_id?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags: string[];
            /** Trace Id */
            trace_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Ordering Mode
             * @enum {string}
             */
            ordering_mode: "sequence" | "time";
        };
        /** EventResponse */
        EventResponse: {
            /** Event Id */
            event_id: string;
            /** Request Id */
            request_id: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "duplicate" | "conflict";
        };
        /** ExpensiveRun */
        ExpensiveRun: {
            /** Agent */
            agent: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Name */
            name: string | null;
            /** Project Id */
            project_id: string;
            /** Retry Count */
            retry_count: number;
            /** Retry Usd */
            retry_usd: number;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** FailureDay */
        FailureDay: {
            /** Blocked */
            blocked: number;
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Failed */
            failed: number;
            /**
             * Failure Rate
             * @description (failed + blocked) / finished, as in `rates`.
             */
            failure_rate: number | null;
            /** Finished */
            finished: number;
            /** Success */
            success: number;
            /** Timed Out */
            timed_out: number;
            /**
             * Timeout Rate
             * @description timed out / finished, as in `rates`.
             */
            timeout_rate: number | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** IssueOut */
        IssueOut: {
            /** Code */
            code: string;
            /** Loc */
            loc: (string | number)[];
            /** Message */
            message: string;
        };
        /**
         * OtherBucket
         * @description Everything beyond the top-N groups: response size does not depend on how many names exist.
         */
        OtherBucket: {
            /** Calls */
            calls: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Groups
             * @description How many groups are folded into this bucket.
             */
            groups: number;
        };
        /**
         * Percentiles
         * @description Approximate: read from duration histograms with about 10% wide buckets (ADR-043).
         */
        Percentiles: {
            /** Count */
            count: number;
            /** P50 Ms */
            p50_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
        };
        /** PerformanceReport */
        PerformanceReport: {
            llm: components["schemas"]["Percentiles"];
            run: components["schemas"]["Percentiles"];
            /** Slow Operations */
            slow_operations: components["schemas"]["SlowOperation"][];
            tool: components["schemas"]["Percentiles"];
            window: components["schemas"]["Window"];
        };
        /** PriceOut */
        PriceOut: {
            /** Cached Input Per Million */
            cached_input_per_million: string | null;
            /** Currency */
            currency: string;
            /** Input Per Million */
            input_per_million: string;
            /** Model Pattern */
            model_pattern: string;
            /**
             * Origin
             * @description `builtin` or `override`.
             */
            origin: string;
            /** Output Per Million */
            output_per_million: string;
            /** Pricing Version */
            pricing_version: string;
            /**
             * Project Id
             * @description Set when an override applies to one project only.
             */
            project_id: string | null;
            /** Provider */
            provider: string | null;
            /** Request Price */
            request_price: string;
            /** Source */
            source: string;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
        };
        /** PricingOut */
        PricingOut: {
            /** Prices */
            prices: components["schemas"]["PriceOut"][];
        };
        /** Rates */
        Rates: {
            /**
             * Failure Rate
             * @description (failed + blocked) / finished
             */
            failure_rate: number | null;
            /**
             * Retry Rate
             * @description runs with at least one retry / runs
             */
            retry_rate: number | null;
            /**
             * Success Rate
             * @description success / finished
             */
            success_rate: number | null;
            /**
             * Timeout Rate
             * @description timed out / finished
             */
            timeout_rate: number | null;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ReliabilityReport */
        ReliabilityReport: {
            /** Failure Trend */
            failure_trend: components["schemas"]["FailureDay"][];
            rates: components["schemas"]["Rates"];
            /** Retry Heavy Runs */
            retry_heavy_runs: components["schemas"]["RetryHeavyRun"][];
            runs: components["schemas"]["RunCounts"];
            /** Tools */
            tools: components["schemas"]["ToolReliability"][];
            tools_other: components["schemas"]["OtherBucket"] | null;
            window: components["schemas"]["Window"];
        };
        /**
         * RetryBreakdown
         * @description Spec §24: how much of the cost came from retries.
         */
        RetryBreakdown: {
            /** Initial Usd */
            initial_usd: number;
            /**
             * Retries Unattributed
             * @description `retry.attempted` events with no span id: counted, but no cost attributed.
             */
            retries_unattributed: number;
            /** Retry Share */
            retry_share: number | null;
            /** Retry Usd */
            retry_usd: number;
            /** Runs With Retry Cost */
            runs_with_retry_cost: number;
            /** Total Usd */
            total_usd: number;
        };
        /** RetryHeavyRun */
        RetryHeavyRun: {
            /** Agent */
            agent: string | null;
            /** Cost Usd */
            cost_usd: number;
            /** Name */
            name: string | null;
            /** Project Id */
            project_id: string;
            /** Retry Count */
            retry_count: number;
            /** Retry Usd */
            retry_usd: number;
            /** Run Id */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
        };
        /** RunCounts */
        RunCounts: {
            /**
             * Active
             * @description Queued, running or waiting.
             */
            active: number;
            /** Blocked */
            blocked: number;
            /** Cancelled */
            cancelled: number;
            /** Failed */
            failed: number;
            /**
             * Finished
             * @description Success, failed, timed out or blocked (cancelled excluded).
             */
            finished: number;
            /** Success */
            success: number;
            /** Timed Out */
            timed_out: number;
            /** Total */
            total: number;
        };
        /** RunOut */
        RunOut: {
            /**
             * Agent Id
             * @description Agent slug of the run's earliest event.
             */
            agent_id: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Id */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string | null;
            /**
             * Ordering Mode
             * @enum {string}
             */
            ordering_mode: "sequence" | "time";
            /** Project Id */
            project_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "WAITING" | "WAITING_FOR_APPROVAL" | "SUCCESS" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "BLOCKED";
            /**
             * Summary
             * @description Derived from events; see docs/architecture/api-v1.md.
             */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Summary State
             * @description `processing` while events wait to be folded into the summary; `failed` if summarization was dead-lettered and needs an operator (`jobs-retry`).
             * @enum {string}
             */
            summary_state: "current" | "processing" | "failed";
            /** Summary Version */
            summary_version: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SlowOperation */
        SlowOperation: {
            /** Calls */
            calls: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** P50 Ms */
            p50_ms: number | null;
            /** P95 Ms */
            p95_ms: number | null;
        };
        /** SpanOut */
        SpanOut: {
            /** Agent Id */
            agent_id: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Ended At */
            ended_at: string | null;
            /** Event Count */
            event_count: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            /** Name */
            name: string | null;
            /** Parent Span Id */
            parent_span_id: string | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /** SpanPage */
        SpanPage: {
            /** Items */
            items: components["schemas"]["SpanOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SpanRate */
        SpanRate: {
            /**
             * Calls
             * @description Spans that finished with a status.
             */
            calls: number;
            /** Success Rate */
            success_rate: number | null;
        };
        /** Summary */
        Summary: {
            /**
             * Active Agents
             * @description Agents with a run in progress (at most 10).
             */
            active_agents: string[];
            behaviour: components["schemas"]["Behaviour"];
            cost: components["schemas"]["CostHeadline"];
            /** @description Model calls; `1 - success_rate` is the request failure rate. */
            llm: components["schemas"]["SpanRate"];
            rates: components["schemas"]["Rates"];
            run_latency: components["schemas"]["Percentiles"];
            runs: components["schemas"]["RunCounts"];
            tools: components["schemas"]["SpanRate"];
            window: components["schemas"]["Window"];
        };
        /** ToolReliability */
        ToolReliability: {
            /** Calls */
            calls: number;
            /** Name */
            name: string;
            /** P95 Ms */
            p95_ms: number | null;
            /** Success Rate */
            success_rate: number | null;
        };
        /** Window */
        Window: {
            /**
             * End
             * Format: date-time
             * @description Exclusive, UTC midnight.
             */
            end: string;
            /**
             * Start
             * Format: date-time
             * @description Inclusive UTC midnight. Windows are whole UTC days; requests snap outward.
             */
            start: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    cost_v1_analytics_cost_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
                /** @description Groups listed before `other`. */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostReport"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project not found or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid (for example a window over 92 days). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The query timed out or a dependency is unavailable; retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    performance_v1_analytics_performance_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
                /** @description Groups listed before `other`. */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerformanceReport"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project not found or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid (for example a window over 92 days). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The query timed out or a dependency is unavailable; retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reliability_v1_analytics_reliability_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
                /** @description Groups listed before `other`. */
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReliabilityReport"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project not found or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid (for example a window over 92 days). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The query timed out or a dependency is unavailable; retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    summary_v1_analytics_summary_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project not found or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid (for example a window over 92 days). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The query timed out or a dependency is unavailable; retry. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ingest_event_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Malformed batch or unsupported schema version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `events:write` or is not bound to a project. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Body (compressed or decompressed) or event too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not application/json, or an unsupported Content-Encoding. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The event is invalid (single-event endpoint). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded; honour `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ingest_batch_v1_events_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Malformed batch or unsupported schema version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `events:write` or is not bound to a project. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Body (compressed or decompressed) or event too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not application/json, or an unsupported Content-Encoding. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The event is invalid (single-event endpoint). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded; honour `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_prices_v1_pricing_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Project not found or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                status?: ("QUEUED" | "RUNNING" | "WAITING" | "WAITING_FOR_APPROVAL" | "SUCCESS" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "BLOCKED")[] | null;
                agent_id?: string | null;
                project_id?: string | null;
                started_after?: string | null;
                started_before?: string | null;
                sort?: "-started_at" | "started_at";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description The run already existed (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description That run id belongs to another project. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                event_type?: string[] | null;
                status?: ("success" | "error" | "timeout" | "cancelled" | "blocked")[] | null;
                span_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description CURSOR_STALE: restart paging from the start. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_event_v1_runs__run_id__events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_spans_v1_runs__run_id__spans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    stream_run_v1_runs__run_id__stream_get: {
        parameters: {
            query?: {
                last_event_id?: string | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `runs:read`. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description STREAM_LIMIT: too many open streams for this server or key; honour Retry-After. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
