/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a single event */
        post: operations["ingest_event_v1_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a batch of events
         * @description Accepts `{batch_id?, sent_at?, events: [...]}` (at most 1000 events, 5 MiB, optionally gzip). `202` means the valid events are committed. Invalid events are reported per event in `errors` and do not affect the others. Retrying a batch is safe.
         */
        post: operations["ingest_batch_v1_events_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List runs
         * @description Newest first by default. Page with `next_cursor`; filters combine with AND.
         */
        get: operations["list_runs_v1_runs_get"];
        put?: never;
        /**
         * Create a run explicitly
         * @description Optional: the first event for an unseen run id creates the run anyway. Idempotent on `run_id`. Needs a project-bound key with `events:write`.
         */
        post: operations["create_run_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a run */
        get: operations["get_run_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a run's events in canonical order
         * @description Ordered by sequence when every event of the run has one, otherwise by time (`ordering_mode`). Payloads are omitted; fetch one event for its payload.
         */
        get: operations["list_events_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one event, including its inline payload */
        get: operations["get_event_v1_runs__run_id__events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/runs/{run_id}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a run's spans
         * @description Derived from events; an empty list while the run is still `processing`.
         */
        get: operations["list_spans_v1_runs__run_id__spans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchResponse */
        BatchResponse: {
            /**
             * Accepted
             * @description Events stored by this request.
             */
            accepted: number;
            /** Batch Id */
            batch_id: string | null;
            /**
             * Conflicts
             * @description Events whose id exists with different content (kept first).
             */
            conflicts: number;
            /**
             * Duplicates
             * @description Events already stored with identical content.
             */
            duplicates: number;
            /** Errors */
            errors: components["schemas"]["EventErrorOut"][];
            /**
             * Rejected
             * @description Events that were not stored; see `errors`.
             */
            rejected: number;
            /** Request Id */
            request_id: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Agent Id */
            agent_id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            category: components["schemas"]["ErrorCategory"];
            /**
             * Code
             * @description Stable machine-readable code, e.g. RUN_NOT_FOUND.
             */
            code: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
            /** Message */
            message: string;
            /**
             * Request Id
             * @description Also in the X-Request-ID response header.
             */
            request_id: string | null;
            /**
             * Retryable
             * @description Whether retrying the same request may succeed.
             */
            retryable: boolean;
        };
        /**
         * ErrorCategory
         * @enum {string}
         */
        ErrorCategory: "AUTHENTICATION" | "AUTHORIZATION" | "VALIDATION" | "RATE_LIMIT" | "DEPENDENCY" | "TIMEOUT" | "CONFLICT" | "NOT_FOUND" | "POLICY" | "INTERNAL";
        /**
         * ErrorEnvelope
         * @description The one error shape of every non-2xx response (spec §101.2).
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * EventErrorOut
         * @description Why one event of a batch was not stored.
         */
        EventErrorOut: {
            /** Code */
            code: string;
            /**
             * Event Id
             * @description The event's id, when it was readable.
             */
            event_id: string | null;
            /**
             * Index
             * @description Position of the event in the submitted `events` array.
             */
            index: number;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["IssueOut"][];
        };
        /**
         * EventOut
         * @description A stored event as returned by the API. `payload` is only present on the detail endpoint.
         */
        EventOut: {
            /** Agent Id */
            agent_id: string;
            /** Agent Version */
            agent_version?: string | null;
            /** Attributes */
            attributes: {
                [key: string]: unknown;
            };
            /** Duration Ms */
            duration_ms?: number | null;
            /** Event Id */
            event_id: string;
            /** Event Type */
            event_type: string;
            /** Has Payload */
            has_payload: boolean;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Parent Span Id */
            parent_span_id?: string | null;
            /**
             * Payload
             * @description Inline payload; omitted from lists (`has_payload` says if present).
             */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Payload Ref */
            payload_ref?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Run Id */
            run_id: string;
            /** Schema Version */
            schema_version: string;
            /** Sdk */
            sdk?: {
                [key: string]: unknown;
            } | null;
            /** Sequence */
            sequence?: number | null;
            /** Span Id */
            span_id?: string | null;
            /** Status */
            status?: string | null;
            /** Tags */
            tags: string[];
            /** Trace Id */
            trace_id: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** EventPage */
        EventPage: {
            /** Items */
            items: components["schemas"]["EventOut"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Ordering Mode
             * @enum {string}
             */
            ordering_mode: "sequence" | "time";
        };
        /** EventResponse */
        EventResponse: {
            /** Event Id */
            event_id: string;
            /** Request Id */
            request_id: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "duplicate" | "conflict";
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** IssueOut */
        IssueOut: {
            /** Code */
            code: string;
            /** Loc */
            loc: (string | number)[];
            /** Message */
            message: string;
        };
        /** ReadyResponse */
        ReadyResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** RunOut */
        RunOut: {
            /**
             * Agent Id
             * @description Agent slug of the run's earliest event.
             */
            agent_id: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Id */
            id: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string | null;
            /**
             * Ordering Mode
             * @enum {string}
             */
            ordering_mode: "sequence" | "time";
            /** Project Id */
            project_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "QUEUED" | "RUNNING" | "WAITING" | "WAITING_FOR_APPROVAL" | "SUCCESS" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "BLOCKED";
            /**
             * Summary
             * @description Derived from events; see docs/architecture/api-v1.md.
             */
            summary: {
                [key: string]: unknown;
            };
            /**
             * Summary State
             * @description `processing` while events wait to be folded into the summary; `failed` if summarization was dead-lettered and needs an operator (`jobs-retry`).
             * @enum {string}
             */
            summary_state: "current" | "processing" | "failed";
            /** Summary Version */
            summary_version: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunPage */
        RunPage: {
            /** Items */
            items: components["schemas"]["RunOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** SpanOut */
        SpanOut: {
            /** Agent Id */
            agent_id: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Ended At */
            ended_at: string | null;
            /** Event Count */
            event_count: number;
            /** Id */
            id: string;
            /** Kind */
            kind: string | null;
            /** Name */
            name: string | null;
            /** Parent Span Id */
            parent_span_id: string | null;
            /** Run Id */
            run_id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string | null;
            /** Trace Id */
            trace_id: string;
        };
        /** SpanPage */
        SpanPage: {
            /** Items */
            items: components["schemas"]["SpanOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ingest_event_v1_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Malformed batch or unsupported schema version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `events:write` or is not bound to a project. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Body (compressed or decompressed) or event too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not application/json, or an unsupported Content-Encoding. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The event is invalid (single-event endpoint). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded; honour `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    ingest_batch_v1_events_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Malformed batch or unsupported schema version. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks `events:write` or is not bound to a project. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Body (compressed or decompressed) or event too large. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not application/json, or an unsupported Content-Encoding. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The event is invalid (single-event endpoint). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Rate limit exceeded; honour `Retry-After`. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_runs_v1_runs_get: {
        parameters: {
            query?: {
                status?: ("QUEUED" | "RUNNING" | "WAITING" | "WAITING_FOR_APPROVAL" | "SUCCESS" | "FAILED" | "CANCELLED" | "TIMED_OUT" | "BLOCKED")[] | null;
                agent_id?: string | null;
                project_id?: string | null;
                started_after?: string | null;
                started_before?: string | null;
                sort?: "-started_at" | "started_at";
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_run_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description The run already existed (idempotent). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description That run id belongs to another project. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_run_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_events_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                event_type?: string[] | null;
                status?: ("success" | "error" | "timeout" | "cancelled" | "blocked")[] | null;
                span_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description CURSOR_STALE: restart paging from the start. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_event_v1_runs__run_id__events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOut"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_spans_v1_runs__run_id__spans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpanPage"];
                };
            };
            /** @description Missing, malformed, unknown, revoked or expired API key. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description The key lacks the required scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not found, or not visible to this key (never reveals other tenants). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A parameter or the request body is invalid. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description A dependency is unavailable; retry with backoff. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
